##服务端口和项目名称
server:
  port: 8881
  servlet:
    context-path: /
    
# spring配置
spring: 
  application:
    name: isheng-tkt-web-admin
  profiles:
    active: dev # 使用开发环境
     
  mvc: 
    view:
      prefix: /
      suffix: .html
    async:
      request-timeout: 3000
    favicon:
      enabled: false
      
          
  
      
      
   
    
    
  
  
